/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations/index'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as IntegrationsTradierRouteImport } from './routes/integrations/tradier'
import { Route as IntegrationsSchwabRouteImport } from './routes/integrations/schwab'
import { Route as IntegrationsDiscordRouteImport } from './routes/integrations/discord'
import { Route as ForDiscordOptionsTradersRouteImport } from './routes/for/discord-options-traders'
import { Route as DesktopFilenameRouteImport } from './routes/desktop/$filename'
import { Route as CompareTradelabsRouteImport } from './routes/compare/tradelabs'
import { Route as CompareNyriaRouteImport } from './routes/compare/nyria'
import { Route as CompareManualCopyRouteImport } from './routes/compare/manual-copy'
import { Route as CompareBotifytradesRouteImport } from './routes/compare/botifytrades'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as ApiDesktopAuthRouteImport } from './routes/api/desktop/auth'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsTradierRoute = IntegrationsTradierRouteImport.update({
  id: '/integrations/tradier',
  path: '/integrations/tradier',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsSchwabRoute = IntegrationsSchwabRouteImport.update({
  id: '/integrations/schwab',
  path: '/integrations/schwab',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsDiscordRoute = IntegrationsDiscordRouteImport.update({
  id: '/integrations/discord',
  path: '/integrations/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ForDiscordOptionsTradersRoute =
  ForDiscordOptionsTradersRouteImport.update({
    id: '/for/discord-options-traders',
    path: '/for/discord-options-traders',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesktopFilenameRoute = DesktopFilenameRouteImport.update({
  id: '/desktop/$filename',
  path: '/desktop/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareTradelabsRoute = CompareTradelabsRouteImport.update({
  id: '/compare/tradelabs',
  path: '/compare/tradelabs',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareNyriaRoute = CompareNyriaRouteImport.update({
  id: '/compare/nyria',
  path: '/compare/nyria',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareManualCopyRoute = CompareManualCopyRouteImport.update({
  id: '/compare/manual-copy',
  path: '/compare/manual-copy',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareBotifytradesRoute = CompareBotifytradesRouteImport.update({
  id: '/compare/botifytrades',
  path: '/compare/botifytrades',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiDesktopAuthRoute = ApiDesktopAuthRouteImport.update({
  id: '/api/desktop/auth',
  path: '/api/desktop/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reviews': typeof ReviewsRoute
  '/risk': typeof RiskRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/compare/botifytrades': typeof CompareBotifytradesRoute
  '/compare/manual-copy': typeof CompareManualCopyRoute
  '/compare/nyria': typeof CompareNyriaRoute
  '/compare/tradelabs': typeof CompareTradelabsRoute
  '/desktop/$filename': typeof DesktopFilenameRoute
  '/for/discord-options-traders': typeof ForDiscordOptionsTradersRoute
  '/integrations/discord': typeof IntegrationsDiscordRoute
  '/integrations/schwab': typeof IntegrationsSchwabRoute
  '/integrations/tradier': typeof IntegrationsTradierRoute
  '/compare/': typeof CompareIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desktop/auth': typeof ApiDesktopAuthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reviews': typeof ReviewsRoute
  '/risk': typeof RiskRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/compare/botifytrades': typeof CompareBotifytradesRoute
  '/compare/manual-copy': typeof CompareManualCopyRoute
  '/compare/nyria': typeof CompareNyriaRoute
  '/compare/tradelabs': typeof CompareTradelabsRoute
  '/desktop/$filename': typeof DesktopFilenameRoute
  '/for/discord-options-traders': typeof ForDiscordOptionsTradersRoute
  '/integrations/discord': typeof IntegrationsDiscordRoute
  '/integrations/schwab': typeof IntegrationsSchwabRoute
  '/integrations/tradier': typeof IntegrationsTradierRoute
  '/compare': typeof CompareIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desktop/auth': typeof ApiDesktopAuthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/download': typeof DownloadRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reviews': typeof ReviewsRoute
  '/risk': typeof RiskRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/compare/botifytrades': typeof CompareBotifytradesRoute
  '/compare/manual-copy': typeof CompareManualCopyRoute
  '/compare/nyria': typeof CompareNyriaRoute
  '/compare/tradelabs': typeof CompareTradelabsRoute
  '/desktop/$filename': typeof DesktopFilenameRoute
  '/for/discord-options-traders': typeof ForDiscordOptionsTradersRoute
  '/integrations/discord': typeof IntegrationsDiscordRoute
  '/integrations/schwab': typeof IntegrationsSchwabRoute
  '/integrations/tradier': typeof IntegrationsTradierRoute
  '/compare/': typeof CompareIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desktop/auth': typeof ApiDesktopAuthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reviews'
    | '/risk'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/billing'
    | '/connections'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/compare/botifytrades'
    | '/compare/manual-copy'
    | '/compare/nyria'
    | '/compare/tradelabs'
    | '/desktop/$filename'
    | '/for/discord-options-traders'
    | '/integrations/discord'
    | '/integrations/schwab'
    | '/integrations/tradier'
    | '/compare/'
    | '/integrations/'
    | '/api/auth/$'
    | '/api/desktop/auth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reviews'
    | '/risk'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/billing'
    | '/connections'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/compare/botifytrades'
    | '/compare/manual-copy'
    | '/compare/nyria'
    | '/compare/tradelabs'
    | '/desktop/$filename'
    | '/for/discord-options-traders'
    | '/integrations/discord'
    | '/integrations/schwab'
    | '/integrations/tradier'
    | '/compare'
    | '/integrations'
    | '/api/auth/$'
    | '/api/desktop/auth'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/download'
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reviews'
    | '/risk'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/_authenticated/billing'
    | '/_authenticated/connections'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/compare/botifytrades'
    | '/compare/manual-copy'
    | '/compare/nyria'
    | '/compare/tradelabs'
    | '/desktop/$filename'
    | '/for/discord-options-traders'
    | '/integrations/discord'
    | '/integrations/schwab'
    | '/integrations/tradier'
    | '/compare/'
    | '/integrations/'
    | '/api/auth/$'
    | '/api/desktop/auth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ReviewsRoute: typeof ReviewsRoute
  RiskRoute: typeof RiskRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  CompareBotifytradesRoute: typeof CompareBotifytradesRoute
  CompareManualCopyRoute: typeof CompareManualCopyRoute
  CompareNyriaRoute: typeof CompareNyriaRoute
  CompareTradelabsRoute: typeof CompareTradelabsRoute
  DesktopFilenameRoute: typeof DesktopFilenameRoute
  ForDiscordOptionsTradersRoute: typeof ForDiscordOptionsTradersRoute
  IntegrationsDiscordRoute: typeof IntegrationsDiscordRoute
  IntegrationsSchwabRoute: typeof IntegrationsSchwabRoute
  IntegrationsTradierRoute: typeof IntegrationsTradierRoute
  CompareIndexRoute: typeof CompareIndexRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDesktopAuthRoute: typeof ApiDesktopAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/tradier': {
      id: '/integrations/tradier'
      path: '/integrations/tradier'
      fullPath: '/integrations/tradier'
      preLoaderRoute: typeof IntegrationsTradierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/schwab': {
      id: '/integrations/schwab'
      path: '/integrations/schwab'
      fullPath: '/integrations/schwab'
      preLoaderRoute: typeof IntegrationsSchwabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/discord': {
      id: '/integrations/discord'
      path: '/integrations/discord'
      fullPath: '/integrations/discord'
      preLoaderRoute: typeof IntegrationsDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/discord-options-traders': {
      id: '/for/discord-options-traders'
      path: '/for/discord-options-traders'
      fullPath: '/for/discord-options-traders'
      preLoaderRoute: typeof ForDiscordOptionsTradersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop/$filename': {
      id: '/desktop/$filename'
      path: '/desktop/$filename'
      fullPath: '/desktop/$filename'
      preLoaderRoute: typeof DesktopFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/tradelabs': {
      id: '/compare/tradelabs'
      path: '/compare/tradelabs'
      fullPath: '/compare/tradelabs'
      preLoaderRoute: typeof CompareTradelabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/nyria': {
      id: '/compare/nyria'
      path: '/compare/nyria'
      fullPath: '/compare/nyria'
      preLoaderRoute: typeof CompareNyriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/manual-copy': {
      id: '/compare/manual-copy'
      path: '/compare/manual-copy'
      fullPath: '/compare/manual-copy'
      preLoaderRoute: typeof CompareManualCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/botifytrades': {
      id: '/compare/botifytrades'
      path: '/compare/botifytrades'
      fullPath: '/compare/botifytrades'
      preLoaderRoute: typeof CompareBotifytradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/desktop/auth': {
      id: '/api/desktop/auth'
      path: '/api/desktop/auth'
      fullPath: '/api/desktop/auth'
      preLoaderRoute: typeof ApiDesktopAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DownloadRoute: DownloadRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ReviewsRoute: ReviewsRoute,
  RiskRoute: RiskRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  CompareBotifytradesRoute: CompareBotifytradesRoute,
  CompareManualCopyRoute: CompareManualCopyRoute,
  CompareNyriaRoute: CompareNyriaRoute,
  CompareTradelabsRoute: CompareTradelabsRoute,
  DesktopFilenameRoute: DesktopFilenameRoute,
  ForDiscordOptionsTradersRoute: ForDiscordOptionsTradersRoute,
  IntegrationsDiscordRoute: IntegrationsDiscordRoute,
  IntegrationsSchwabRoute: IntegrationsSchwabRoute,
  IntegrationsTradierRoute: IntegrationsTradierRoute,
  CompareIndexRoute: CompareIndexRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDesktopAuthRoute: ApiDesktopAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
